# Base URL
baseurl: ''

# Site live URL
url: http://hackermo.de

# Localhost 
#url: http://127.0.0.1:4000  


name: hackermode
description: "Modi's TIL blog for the developermode project"
meta_description: > # 
  Abhishek Modi's TIL blog for the developermode project.
  http://akmodi.com http://developermo.de

# Harmony theme configuration. Please change accordingly.
harmony:
  name: hackermode
  # Little description about your site
  description: "Modi's TIL blog for the developermode project"
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   Abhishek Modi's TIL blog for the developermode project.
   http://akmodi.com http://developermo.de
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Abhishek Modi
    email: init@akmodi.com
    url: http://akmodi.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: modi95
    twitter: vious21
    facebook: akmodi1995
    gplus: +akmodi
    dribble: akmodi
    pinterest: akmodi
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

paginate: 15

gems: [jekyll-paginate]
